# Generated by Django 5.1 on 2024-08-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic_Registration',
            fields=[
                ('clinic_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clinic_name', models.CharField(blank=True, max_length=30, null=True)),
                ('clinic_mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('clinic_username', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
