# Generated by Django 5.1 on 2024-08-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch_Create',
            fields=[
                ('branch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('clinic', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.clinic_registration')),
            ],
        ),
    ]
