# Generated by Django 5.1 on 2024-10-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_patient_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otp',
            name='is_resend',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
