# Generated by Django 5.1 on 2024-08-28 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_branch_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Allotment',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_doctor', models.BooleanField(default=False)),
                ('is_receptionist', models.BooleanField(default=False)),
                ('is_nurse', models.BooleanField(default=False)),
                ('is_pharmacist', models.BooleanField(default=False)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('branch_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.branch_create')),
                ('clinic_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.clinic_registration')),
            ],
        ),
    ]
