# Generated by Django 5.1 on 2024-10-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_otp_is_resend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otp',
            name='resend_count',
            field=models.IntegerField(default=0),
        ),
    ]
