# Generated by Django 5.1 on 2024-08-28 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_staff_allotment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_MetaData',
            fields=[
                ('staff_meta_id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, null=True, unique=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, default=30, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=20, null=True)),
                ('consulting_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('permanent_address', models.TextField(blank=True, null=True)),
                ('speciality', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_id', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, to='app.staff_allotment')),
            ],
            options={
                'db_table': 'Staff_MetaData',
            },
        ),
    ]
