# Generated by Django 5.1 on 2024-08-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_staff_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Metadata',
            fields=[
                ('patient_id', models.BigAutoField(db_column='patient_id', primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=30, null=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('appointment_id', models.IntegerField(blank=True, null=True)),
                ('appointment_type', models.CharField(blank=True, choices=[('Scheduled', 'Scheduled'), ('Queue', 'Queue')], max_length=50, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('from_time', models.TimeField(blank=True, null=True)),
                ('to_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=True)),
            ],
        ),
    ]
