# Generated by Django 5.1 on 2024-10-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_otp_resend_count'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='slot',
            table='slots',
        ),
    ]
