# Generated by Django 5.1 on 2024-08-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_patient_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Registration',
            fields=[
                ('patient_id', models.BigAutoField(db_column='patient_id', primary_key=True, serialize=False)),
                ('branch_id', models.BigIntegerField(default=True, null=True)),
                ('clinic_id', models.BigIntegerField(default=True, null=True)),
                ('patient_name', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('patient_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('EHS', 'EHS')], max_length=10, null=True)),
                ('is_registered', models.BooleanField(default=True)),
            ],
        ),
    ]
