# Generated by Django 5.1 on 2024-10-29 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_staff_metadata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff_metadata',
            table=None,
        ),
    ]
