# Generated by Django 5.1 on 2024-08-29 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_patient_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient_Registration',
        ),
    ]
