# Generated by Django 5.1 on 2024-10-29 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_staff_metadata_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staff_metadata',
            table='staff_MetaData',
        ),
    ]
