# Generated by Django 5.1 on 2024-08-29 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_patient_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Appointment',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('patient', models.BigIntegerField(blank=True, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
                ('appointment_type', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Queue', 'Queue')], max_length=50)),
                ('appointment_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_registered', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(limit_choices_to={'is_doctor': True}, on_delete=django.db.models.deletion.CASCADE, to='app.staff_allotment')),
            ],
        ),
    ]
