# Generated by Django 5.1 on 2024-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_patient_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_registration',
            name='patient_id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
