# Generated by Django 5.1 on 2024-11-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_patient_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_doctors',
            name='department',
            field=models.ForeignKey(db_column='dept_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.doctor_departments', to_field='dept_name'),
        ),
    ]
