# Generated by Django 5.1 on 2024-11-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_top_doctors_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patient_images/'),
        ),
        migrations.AlterField(
            model_name='staff_metadata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff_images/'),
        ),
    ]
