# Generated by Django 5.1 on 2024-08-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_patient_registration_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_registration',
            name='patient_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
