# Generated by Django 5.1 on 2024-11-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_patient_image_alter_staff_metadata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_metadata',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_metadata',
            name='experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
