# Generated by Django 5.1 on 2024-08-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_patient_registration_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_appointment',
            name='patient',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
