# Generated by Django 5.1 on 2024-11-07 11:21

import app.models.Staff_models
import app.models.patient_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_staff_metadata_description_staff_metadata_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.patient_models.patient_image_path),
        ),
        migrations.AlterField(
            model_name='staff_metadata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.Staff_models.staff_image_path),
        ),
    ]
