# Generated by Django 5.1 on 2024-09-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_user_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_id', models.IntegerField(blank=True, db_column='company_id', default=1)),
                ('branch_id', models.IntegerField(blank=True, default=1)),
                ('username', models.CharField(blank=True, db_column='username', max_length=50, null=True, unique=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, db_column='age', null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('pincode', models.IntegerField(blank=True, db_column='pincode', null=True)),
                ('registeredat', models.DateTimeField(db_column='registeredAt')),
                ('lastlogin', models.DateTimeField(blank=True, db_column='lastLogin', null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=50, null=True)),
                ('state', models.CharField(blank=True, db_column='state', max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='app.images/')),
                ('is_creator', models.BooleanField(default=False)),
                ('through_google', models.BooleanField(db_column='through_google', default=False)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
