# Generated by Django 5.1 on 2024-09-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Patient',
        ),
    ]
