# Generated by Django 5.1 on 2024-09-10 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_user_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otp',
            name='delete_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 7, 21, 44, 266508, tzinfo=datetime.timezone.utc)),
        ),
    ]
