# Generated by Django 5.1 on 2024-11-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_top_doctors_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_doctors',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
