# Generated by Django 5.1 on 2024-11-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_top_doctors_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_doctors',
            name='department',
            field=models.CharField(db_column='dept_name', max_length=30, null=True, unique=True),
        ),
    ]
