# Generated by Django 5.1 on 2024-09-10 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_otp_delete_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_otp',
            name='purpose',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_otp',
            name='delete_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 7, 23, 59, 109697, tzinfo=datetime.timezone.utc)),
        ),
    ]
