# Generated by Django 5.1 on 2024-09-10 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_user_otp_purpose_alter_user_otp_delete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otp',
            name='delete_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 11, 9, 28, 170641, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='patient',
            table='Patient',
        ),
    ]
