# Generated by Django 5.1 on 2024-11-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_top_doctors_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_metadata',
            name='no_of_patients',
            field=models.IntegerField(default=250),
        ),
    ]
