# Generated by Django 5.1 on 2024-09-10 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_user_otp_delete_at_alter_patient_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otp',
            name='delete_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 11, 37, 28, 751878, tzinfo=datetime.timezone.utc)),
        ),
    ]
