# Generated by Django 5.1 on 2024-11-14 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_staff_metadata_no_of_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet_transactions_credit',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_credit', models.BooleanField()),
                ('to', models.CharField(db_column='to', max_length=40)),
                ('from_username', models.CharField(db_column='from_username', max_length=50)),
                ('is_from', models.CharField(db_column='from', max_length=50)),
                ('current_bal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('to_user_id', models.ForeignKey(blank=True, db_column='to_user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_transacation_credit',
                'managed': True,
            },
        ),
    ]
