# Generated by Django 5.1 on 2024-11-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_notification_user_id_notification_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet_transactions_credit',
            old_name='is_credit',
            new_name='is_received',
        ),
    ]
