# Generated by Django 5.1 on 2024-11-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_is_credit_wallet_transactions_credit_is_received'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet_transactions_debit',
            old_name='is_debit',
            new_name='is_paid',
        ),
    ]
