# Generated by Django 5.1 on 2024-09-11 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_user_otp_delete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otp',
            name='delete_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 5, 26, 17, 741437, tzinfo=datetime.timezone.utc)),
        ),
    ]
