# Generated by Django 5.1 on 2024-09-11 05:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_user_otp_delete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_otp',
            name='delete_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
