# Generated by Django 5.1 on 2024-09-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_Departments',
            fields=[
                ('dept_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=15)),
            ],
        ),
    ]
