# Generated by Django 5.1 on 2024-09-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_doctor_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Symptoms',
            fields=[
                ('symptom_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('symptom_name', models.CharField(blank=True, db_column='symptom', max_length=50, null=True)),
                ('symptom_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
