# Generated by Django 5.1 on 2024-09-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_patient_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_metadata',
            name='profession',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
