# Generated by Django 5.1 on 2024-09-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_staff_metadata_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_metadata',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
