# Generated by Django 5.1 on 2024-09-12 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_staff_metadata_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_doctors',
            fields=[
                ('top_doctor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, max_length=30, null=True)),
                ('doctor_id', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='app.staff_allotment')),
            ],
        ),
    ]
