# Generated by Django 5.1 on 2024-09-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_top_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_metadata',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app.images/'),
        ),
    ]
