# Generated by Django 5.1 on 2024-09-13 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_staff_metadata_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='top_doctors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='app.images/'),
        ),
        migrations.AlterField(
            model_name='top_doctors',
            name='department',
            field=models.ForeignKey(db_column='department', default=1, on_delete=django.db.models.deletion.CASCADE, to='app.doctor_departments'),
            preserve_default=False,
        ),
    ]
