# Generated by Django 5.1 on 2024-09-13 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_doctor_departments_dept_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_doctors',
            name='department',
            field=models.ForeignKey(db_column='department', on_delete=django.db.models.deletion.CASCADE, to='app.doctor_departments', to_field='dept_name'),
        ),
    ]
