# Generated by Django 5.1 on 2024-09-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_alter_top_doctors_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_departments',
            name='dept_name',
            field=models.CharField(db_column='dept_name', max_length=30, unique=True),
        ),
    ]
