# Generated by Django 5.1 on 2024-09-13 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_doctor_departments_dept_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='top_doctors',
            name='department',
            field=models.ForeignKey(db_column='dept_name', on_delete=django.db.models.deletion.CASCADE, to='app.doctor_departments', to_field='dept_name'),
        ),
    ]
