# Generated by Django 5.1 on 2024-09-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_top_doctors_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_metadata',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
