# Generated by Django 5.1 on 2024-09-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_alter_staff_metadata_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('promotion_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='app.images/')),
            ],
        ),
    ]
