# Generated by Django 5.1 on 2024-09-17 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('wallet_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wallet_bal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('email', models.ForeignKey(blank=True, db_column='email', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet user email+', to='app.patient', to_field='email')),
                ('user_id', models.ForeignKey(blank=True, db_column='to_user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
