# Generated by Django 5.1 on 2024-09-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='user_id',
            new_name='patient_id',
        ),
    ]
