# Generated by Django 5.1 on 2024-09-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_rename_user_id_wallet_patient_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='wallet',
        ),
    ]
