# Generated by Django 5.1 on 2024-09-17 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_wallet_options_alter_wallet_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='wallet_transactions_debit',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_debit', models.BooleanField(default=True)),
                ('to', models.CharField(db_column='to', max_length=40)),
                ('current_bal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('patient_id', models.ForeignKey(blank=True, db_column='to_patient_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
            options={
                'db_table': 'wallet_transacation_debit',
                'managed': True,
            },
        ),
    ]
