# Generated by Django 5.1 on 2024-09-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('day_id', models.BigAutoField(db_column='day_id', primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=10)),
            ],
        ),
    ]
