# Generated by Django 5.1 on 2024-09-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_metadata',
            name='Fullname_IMC',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='staff_metadata',
            name='IMC_Reg_No',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='staff_metadata',
            name='slot_duration',
            field=models.IntegerField(default=30),
        ),
    ]
