# Generated by Django 5.1 on 2024-09-30 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_staff_metadata_fullname_imc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='slots_booked',
            fields=[
                ('slot_id', models.BigAutoField(db_column='slot_id', primary_key=True, serialize=False)),
                ('doctor_id', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='app.staff_allotment')),
            ],
        ),
    ]
