# Generated by Django 5.1 on 2024-09-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_slots_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_metadata',
            name='Days',
            field=models.TextField(blank=True, db_column='Days', null=True),
        ),
    ]
