# Generated by Django 5.1 on 2024-10-01 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_staff_metadata_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Management',
            fields=[
                ('leave_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('staff_id', models.ForeignKey(db_column='staff_id', on_delete=django.db.models.deletion.CASCADE, to='app.staff_allotment')),
            ],
        ),
    ]
