# Generated by Django 5.1 on 2024-10-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_leave_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='on_leave',
            field=models.BooleanField(default=False),
        ),
    ]
