# Generated by Django 5.1 on 2024-10-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_patient_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('coupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=6, unique=True)),
                ('valid_from', models.DateField(null=True)),
                ('valid_till', models.DateField(null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
