# Generated by Django 5.1 on 2024-10-14 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_coupons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon_claimed',
            fields=[
                ('claim_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(blank=True, db_column='user_id', null=True)),
                ('quiz_id', models.BigIntegerField(blank=True, db_column='quiz_id', null=True)),
                ('amount_claimed', models.IntegerField(blank=True, db_column='amount', null=True)),
                ('coupon_id', models.ForeignKey(db_column='coupon_id', on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='app.coupons')),
            ],
        ),
    ]
