# Generated by Django 5.1 on 2024-10-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_coupon_claimed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotted_Images',
            fields=[
                ('image_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Appointment_id', models.BigIntegerField(db_column='Appointment_id')),
                ('spotted_place', models.CharField(blank=True, db_column='symptom', max_length=50, null=True)),
                ('image_1', models.ImageField(upload_to='')),
                ('image_2', models.ImageField(upload_to='')),
            ],
        ),
    ]
