# Generated by Django 5.1 on 2024-10-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_spotted_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Appointment',
            fields=[
                ('appointment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('doctor_id', models.IntegerField(db_column='doctor_id', null=True)),
                ('appointment_date', models.DateField(db_column='appointment date', null=True)),
                ('slot_id', models.IntegerField(db_column='slot id')),
                ('age', models.IntegerField(db_column='age')),
                ('blood_group', models.CharField(blank=True, db_column='blood group', max_length=4, null=True)),
                ('relation', models.CharField(blank=True, db_column='relation', max_length=15, null=True)),
                ('description', models.CharField(blank=True, db_column='description', max_length=500, null=True)),
                ('symptoms', models.CharField(blank=True, db_column='symptoms', max_length=100, null=True)),
                ('total_amount', models.IntegerField(db_column='total amount')),
                ('coupon_used', models.BooleanField(default=False)),
                ('coupon_amount', models.IntegerField(db_column='coupon_amount', default=0)),
                ('net_payable', models.IntegerField(db_column='net payable', default=0)),
            ],
        ),
    ]
