# Generated by Django 5.1 on 2024-10-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_book_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotted_images',
            name='image_1',
            field=models.ImageField(upload_to='E:\\quizapp\\quizapp\\project\\images\\patient images'),
        ),
        migrations.AlterField(
            model_name='spotted_images',
            name='image_2',
            field=models.ImageField(upload_to='E:\\quizapp\\quizapp\\project\\images\\patient images'),
        ),
    ]
