# Generated by Django 5.1 on 2024-10-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_alter_spotted_images_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotted_images',
            name='image_1',
            field=models.ImageField(upload_to='\\patient images'),
        ),
        migrations.AlterField(
            model_name='spotted_images',
            name='image_2',
            field=models.ImageField(upload_to='\\patient images'),
        ),
    ]
