# Generated by Django 5.1 on 2024-10-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_alter_spotted_images_image_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_appointment',
            name='doctor_id',
            field=models.IntegerField(db_column='doctor_id', null=True),
        ),
    ]
