# Generated by Django 5.1 on 2024-10-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_book_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotted_images',
            name='image_1',
            field=models.ImageField(upload_to='patient_images/'),
        ),
        migrations.AlterField(
            model_name='spotted_images',
            name='image_2',
            field=models.ImageField(upload_to='patient_images/'),
        ),
    ]
