# Generated by Django 5.1 on 2024-10-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_spotted_images_image_1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave_Management',
        ),
    ]
