# Generated by Django 5.1 on 2024-10-17 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_delete_leave_management'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
