# Generated by Django 5.1 on 2024-10-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_delete_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_appointment',
            name='slot_id',
        ),
    ]
