# Generated by Django 5.1 on 2024-10-17 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_slot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
