# Generated by Django 5.1 on 2024-10-17 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appointment',
            name='slot_id',
            field=models.ForeignKey(db_column='slot_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.slot'),
        ),
    ]
