# Generated by Django 5.1 on 2024-10-17 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_book_appointment_slot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_appointment',
            name='doctor_id',
        ),
    ]
