# Generated by Django 5.1 on 2024-10-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_book_appointment_doctor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appointment',
            name='is_self',
            field=models.BooleanField(default=True),
        ),
    ]
