# Generated by Django 5.1 on 2024-10-17 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_leave_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_appointment',
            name='doctor_id',
            field=models.ForeignKey(db_column='doctor_id', default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.staff_allotment'),
        ),
    ]
