# Generated by Django 5.1 on 2024-10-17 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0076_alter_book_appointment_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_appointment',
            name='doctor_id',
            field=models.ForeignKey(blank=True, db_column='doctor_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.staff_allotment'),
        ),
    ]
