# Generated by Django 5.1 on 2024-10-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0077_alter_book_appointment_doctor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_Appointment',
        ),
    ]
