# Generated by Django 5.1 on 2024-10-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_book_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_symptoms',
            name='symptom_price',
        ),
    ]
