# Generated by Django 5.1 on 2024-10-23 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0080_remove_patient_symptoms_symptom_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_creator',
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updated_at', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
