# Generated by Django 5.1 on 2024-10-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0081_remove_patient_is_creator_patient_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='updated_by',
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
