# Generated by Django 5.1 on 2024-10-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0085_spotted_images_created_at_spotted_images_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_appointment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book_appointment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book_appointment',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='book_appointment',
            name='updated_by',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
