# Generated by Django 5.1 on 2024-10-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_book_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_symptoms',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient_symptoms',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient_symptoms',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='patient_symptoms',
            name='updated_by',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
