# Generated by Django 5.1 on 2024-10-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_staff_allotment_created_at_staff_allotment_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slots_booked',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slots_booked',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slots_booked',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='slots_booked',
            name='updated_by',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
