# Generated by Django 5.1 on 2024-10-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0090_wallet_created_at_wallet_is_active_wallet_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_transactions_debit',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wallet_transactions_debit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='wallet_transactions_debit',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='wallet_transactions_debit',
            name='updated_by',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
